GPIO:
  PB13:
    Label: SWCLK
    Signal: GPIO_Output
  PB14:
    Label: SWDIO
    Signal: GPIO_Output
  PB6:
    Label: NRST
    Signal: GPIO_Output
Peripherals:
  TIM:
    TIM1:
      Channels:
        CH2:
          Label: TIM1
          PWM: true
          Complementary: false
          DutyCycle: null
  ADC: {}
  USB:
    USB: {}
DMA:
  Requests: {}
  Configurations: {}
Timebase:
  Source: SysTick
  IRQ: null
Mcu:
  Family: STM32F1
  Type: STM32F103C8T6
